pipeline {
    agent any

    tools {
        maven "3.9.2"
    }

    environment {
        GITHUB_REPO_CRED = credentials("github-cred")
        GITHUB_REPO_OWNER = "hojagi"
        GITHUB_REPO_NAME = "jenkins"
        GITHUB_REPO_URL = "https://github.com/${GITHUB_REPO_OWNER}/${GITHUB_REPO_NAME}.git"
        VERSION = "1.0.${BUILD_NUMBER}" // global ENVs  ${YOUR_JENKINS_URL}/pipeline-syntax/globals#env
        MAVEN_REPO_PATH = "${WORKSPACE}/.m2/repository"
    }

    stages {
        stage('Build') {
            steps {
                dir('apps/hello-world') {
                    sh "mvn -B -DskipTests -Dmaven.repo.local=${MAVEN_REPO_PATH} -Dversion.application=${env.VERSION} clean package"
                }
            }
        }

        stage('Test') {
            steps {
                dir('apps/hello-world') {
                    sh 'mvn test'
                }
            }
        }

        // stage('Upload') {
        //     when {
        //         expression { BRANCH_NAME == "main" }
        //     }
        //     steps {
        //         dir('apps/hello-world') {
        //             sh "mvn -DskipTests -s settings.xml -Dmaven.repo.local=${MAVEN_REPO_PATH} -Dversion.application=${env.VERSION} deploy"
        //         }
        //     }
        // }
    }

    post {
        success {
            dir('apps/hello-world') {
                junit 'target/surefire-reports/*.xml'
                // archiveArtifacts 'target/*.jar'
            }
        }
    }
}