pipeline {
    agent any
    environment {
        DB_HOST = '192.168.56.112'
        DB_PORT = '5432'
        DB_NAME = 'db_webbooks'
        DB_USER = 'postgres'
        DB_PASSWORD = 'password'
    }

    stages {
        stage('Build and tests') {
            steps {
			    dir('lesson12') {
				    sh "chmod -R 777 webbooks"
				}
                dir('lesson12/webbooks') {
				    
                    //sh "./mvnw -DskipTests clean package"
					sh "./mvnw package"
                }
            }

            post {
                success {
					echo 'Build and tests success complete'
                }
            }
        }
        stage('Build, create artefact and pipeline') {
            steps {
                dir('lesson12/webbooks') {
                    //sh "./mvnw -DskipTests clean package"
					sh "./mvnw package"
                }
            }

            post {
                success {
                    archiveArtifacts '**/target/*.jar'
                }
            }
        }
    }
}