pipeline {
    agent any
//    environment {
//        DB_HOST = '192.168.56.112'
//        DB_PORT = '5432'
//        DB_NAME = 'db_webbooks'
//        DB_USER = 'postgres'
//        DB_PASSWORD = 'password'
//    }

    stages {
        stage('Build and tests') {
		    when {
                branch 'PR-*'
            }
            steps {
			    dir('lesson12') {
				    sh "chmod -R 777 webbooks"
				}
                dir('lesson12/webbooks') {
				    
                    //sh "./mvnw -DskipTests clean package"
					sh "./mvnw package -DDB.url=jdbc:postgresql://192.168.56.112:5432/webbooks"
                }
            }

            post {
                success {
					echo 'Build and tests success complete'
                }
            }
        }
        stage('Build, create artefact and pipeline') {
		    when {
                branch 'main'
            }

            steps {
                dir('lesson12/webbooks') {
                    //sh "./mvnw -DskipTests clean package"
					sh "./mvnw package -DDB.url=jdbc:postgresql://192.168.56.112:5432/webbooks"
                }
            }

            post {
                success {
				    echo 'Build, create artefact and pipeline success'
                    archiveArtifacts '**/target/*.jar'
                }
            }
        }
    }
}